Vagrant.configure("2") do |config|
	config.vm.box = "centos6_64"
    config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"
	config.vm.provision :shell, :path => "bootstrap.sh"
	config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
end
